<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_8,999_w-full bg-puma-black-800 aspect-1-1</name>
   <tag></tag>
   <elementGuidId>4f98e0c0-55d5-43a9-96a9-0b70b775de45</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//ul[@id='product-list-items']/li[2]/a/div/div/div/div/img</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>301c8640-505a-44be-be72-46d233552521</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>w-full bg-puma-black-800 aspect-1-1</value>
      <webElementGuid>982163f0-60a9-41bf-95a3-3c8708571bbb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://images.puma.com/image/upload/f_auto,q_auto,b_rgb:fafafa,w_300,h_300/global/307239/05/sv01/fnd/IND/fmt/png/BMW-M-Motorsport-SPEEDFUSION-Unisex-Sneakers</value>
      <webElementGuid>2803b660-bf21-4bc5-91b3-4875b4d9c48f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>width</name>
      <type>Main</type>
      <value>400</value>
      <webElementGuid>c00d4052-5096-442a-a536-07b1fda77af6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>height</name>
      <type>Main</type>
      <value>400</value>
      <webElementGuid>57277944-60a5-4f91-9cef-a1edba2ea971</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>loading</name>
      <type>Main</type>
      <value>lazy</value>
      <webElementGuid>f4239255-69dd-4d62-9f71-2aef35d62fc6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>alt</name>
      <type>Main</type>
      <value>BMW M Motorsport SPEEDFUSION Unisex Sneakers, Cool Cobalt-PUMA White</value>
      <webElementGuid>289071f4-429a-44cf-88fb-dd11f9813877</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>BMW M Motorsport SPEEDFUSION Unisex Sneakers, Cool Cobalt-PUMA White</value>
      <webElementGuid>44cc9069-f805-4665-a31a-69870fcdad15</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>srcset</name>
      <type>Main</type>
      <value>https://images.puma.com/image/upload/f_auto,q_auto,b_rgb:fafafa,w_300,h_300/global/307239/05/sv01/fnd/IND/fmt/png/BMW-M-Motorsport-SPEEDFUSION-Unisex-Sneakers 300w,https://images.puma.com/image/upload/f_auto,q_auto,b_rgb:fafafa,w_350,h_350/global/307239/05/sv01/fnd/IND/fmt/png/BMW-M-Motorsport-SPEEDFUSION-Unisex-Sneakers 350w,https://images.puma.com/image/upload/f_auto,q_auto,b_rgb:fafafa,w_400,h_400/global/307239/05/sv01/fnd/IND/fmt/png/BMW-M-Motorsport-SPEEDFUSION-Unisex-Sneakers 400w,https://images.puma.com/image/upload/f_auto,q_auto,b_rgb:fafafa,w_450,h_450/global/307239/05/sv01/fnd/IND/fmt/png/BMW-M-Motorsport-SPEEDFUSION-Unisex-Sneakers 450w,https://images.puma.com/image/upload/f_auto,q_auto,b_rgb:fafafa,w_500,h_500/global/307239/05/sv01/fnd/IND/fmt/png/BMW-M-Motorsport-SPEEDFUSION-Unisex-Sneakers 500w,https://images.puma.com/image/upload/f_auto,q_auto,b_rgb:fafafa,w_550,h_550/global/307239/05/sv01/fnd/IND/fmt/png/BMW-M-Motorsport-SPEEDFUSION-Unisex-Sneakers 550w,https://images.puma.com/image/upload/f_auto,q_auto,b_rgb:fafafa,w_600,h_600/global/307239/05/sv01/fnd/IND/fmt/png/BMW-M-Motorsport-SPEEDFUSION-Unisex-Sneakers 600w</value>
      <webElementGuid>bc0de90c-7002-431e-934b-5a93cbdbf7ba</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>sizes</name>
      <type>Main</type>
      <value>(max-width: 539px) 50vw, (min-width: 540px) and (max-width: 1023px) 33vw, (min-width: 1024px) 25vw</value>
      <webElementGuid>b54e6831-dff0-49c1-9b7a-6ebfaac35cd2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;product-list-items&quot;)/li[2]/a[@class=&quot;tw-hqslau tw-xbcb1y&quot;]/div[@class=&quot;relative w-full flex flex-col gap-2&quot;]/div[@class=&quot;relative group&quot;]/div[@class=&quot;flex overflow-x-scroll hover:scroll-snap&quot;]/div[@class=&quot;w-full flex-none transform-gpu&quot;]/img[@class=&quot;w-full bg-puma-black-800 aspect-1-1&quot;]</value>
      <webElementGuid>c0ab8328-d99d-4efa-a65f-06617566974d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//ul[@id='product-list-items']/li[2]/a/div/div/div/div/img</value>
      <webElementGuid>8041ccf7-21c6-42ff-9738-38f695693969</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>//img[@alt='BMW M Motorsport SPEEDFUSION Unisex Sneakers, Cool Cobalt-PUMA White']</value>
      <webElementGuid>9b36b317-8c52-4187-8a30-cdbf6698b40f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[2]/a/div/div/div/div/img</value>
      <webElementGuid>123e2c9d-f8ab-4861-b28a-8de5dccd31bc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = 'https://images.puma.com/image/upload/f_auto,q_auto,b_rgb:fafafa,w_300,h_300/global/307239/05/sv01/fnd/IND/fmt/png/BMW-M-Motorsport-SPEEDFUSION-Unisex-Sneakers' and @alt = 'BMW M Motorsport SPEEDFUSION Unisex Sneakers, Cool Cobalt-PUMA White' and @title = 'BMW M Motorsport SPEEDFUSION Unisex Sneakers, Cool Cobalt-PUMA White']</value>
      <webElementGuid>cf4d88cf-3704-4f90-aac7-f5686cfbaec8</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
