<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_shoes</name>
   <tag></tag>
   <elementGuidId>293b2202-0ae9-4440-adbd-d52dd9dfacda</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='react-autowhatever-1']/div/ul/li/a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>7885b1b4-b971-4cfa-8487-8e4117231075</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/search/?text=shoes</value>
      <webElementGuid>2eab3ac6-d164-4dfd-b414-db6f26b37e5f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>search-suggestionList </value>
      <webElementGuid>4fa228da-041f-4af6-a03d-5f483bb945d6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>shoes</value>
      <webElementGuid>c137d2ee-4a7d-428b-aef1-269ef3de84b1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;react-autowhatever-1&quot;)/div[@class=&quot;autosuggesssion-top-searches&quot;]/ul[@class=&quot;rilrtl-list&quot;]/li[@class=&quot;rilrtl-list-item&quot;]/a[@class=&quot;search-suggestionList&quot;]</value>
      <webElementGuid>50191490-d047-4fba-b3c8-ffdc82b13e3f</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='react-autowhatever-1']/div/ul/li/a</value>
      <webElementGuid>efc69d7b-18c2-43e8-a40d-e6ddfc904aa8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Top Searches'])[1]/following::a[1]</value>
      <webElementGuid>046929e7-78bc-4b3f-832d-bdafebdfb7a9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Kuber Industries'])[1]/following::a[1]</value>
      <webElementGuid>de727f01-7eef-4098-96fc-1559ea9ea7e5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='jackets'])[1]/preceding::a[1]</value>
      <webElementGuid>5f8569b6-1b57-44f0-8db2-7204286163e1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, '/search/?text=shoes')]</value>
      <webElementGuid>6385d165-fcc1-4c16-a480-de5f22926c80</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div/div/ul/li/a</value>
      <webElementGuid>f71219a6-03f9-4fb3-a780-1c7c1f488161</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '/search/?text=shoes' and (text() = 'shoes' or . = 'shoes')]</value>
      <webElementGuid>b961ce27-f2fb-4b6d-b909-cc37da4e5fbb</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
