<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Search</name>
   <tag></tag>
   <elementGuidId>98694d1c-93f9-4359-844a-66e19d69dcd5</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>a.btn.btn-primary.search-table</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='rootCtrlId']/div[3]/div[2]/div/div[2]/a[2]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>32b839d1-44c8-4b34-bf08-2da82b8486cb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn btn-primary search-table</value>
      <webElementGuid>b84b7789-49e9-4b60-a5df-60c0558c614a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-click</name>
      <type>Main</type>
      <value>vm.Search()</value>
      <webElementGuid>f3854d8c-183f-4749-8076-6865c72948ec</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>  Search</value>
      <webElementGuid>1bd38c30-f7d8-464c-baab-e967edb3b73e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;rootCtrlId&quot;)/div[@class=&quot;page-container&quot;]/div[@class=&quot;content-wrapper&quot;]/div[@class=&quot;ng-scope&quot;]/div[@class=&quot;form-group text-right&quot;]/a[@class=&quot;btn btn-primary search-table&quot;]</value>
      <webElementGuid>265b73ca-231e-44c9-98a0-0da06eb2d435</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='rootCtrlId']/div[3]/div[2]/div/div[2]/a[2]</value>
      <webElementGuid>a838b79f-c6a6-4ebc-8fa1-6deebdb89290</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Investment'])[1]/following::a[2]</value>
      <webElementGuid>d1063f4e-12a6-48ec-b083-bab8a7a588ce</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Complaints Policy |'])[1]/preceding::a[1]</value>
      <webElementGuid>67a92b9b-f703-4969-87b6-6e08aaaba3a1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Privacy Policy |'])[1]/preceding::a[2]</value>
      <webElementGuid>49a930ce-a768-4db6-8e00-baf21074c52d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Search']/parent::*</value>
      <webElementGuid>b29ebae8-a986-4b18-b2a0-4fa395b28c88</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>(//a[contains(@href, '')])[26]</value>
      <webElementGuid>064cef81-84f8-4176-bde8-89fff8d1dc73</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//a[2]</value>
      <webElementGuid>f5bd6cb2-bce8-4442-b91b-6ba98c7ad5c1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[(text() = '  Search' or . = '  Search')]</value>
      <webElementGuid>d8789bf0-8779-4930-bb4d-ba493dd023e8</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
