<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_WER-P-0001093</name>
   <tag></tag>
   <elementGuidId>b5f54abf-3fd5-46c0-a709-694e5ab6856b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#1686746797885-9-uiGrid-0006-cell > form[name=&quot;searchPolicy&quot;] > button.link.ng-binding</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>(//button[@type='submit'])[19]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>387a9432-4757-473b-b765-8d917748c521</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>submit</value>
      <webElementGuid>3f318d96-a486-4496-9182-371925728a95</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>link ng-binding</value>
      <webElementGuid>5151f5f8-1dbe-4628-a4c6-a5160dc138bd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>WER-P-0001093</value>
      <webElementGuid>d7c2bf14-d48f-48ad-85ff-33c1fbe67cc4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;1686746797885-9-uiGrid-0006-cell&quot;)/form[@class=&quot;ng-pristine ng-valid ng-scope&quot;]/button[@class=&quot;link ng-binding&quot;]</value>
      <webElementGuid>c859a8d2-cac5-443b-80b3-14a5e6c7a2fc</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//button[@type='submit'])[19]</value>
      <webElementGuid>4ac5f2ba-d2a0-43b4-ac3e-44cf4811212d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='1686746797885-9-uiGrid-0006-cell']/form/button</value>
      <webElementGuid>1b2ec7c3-5364-4fc2-8118-1a0160b83ce2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Bound'])[10]/following::button[1]</value>
      <webElementGuid>166f3d0d-c1cb-411b-bf85-33d1b454b1f3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Renewal'])[1]/following::button[1]</value>
      <webElementGuid>66855191-ad90-412f-b2f4-f4345fb86860</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='CL0004173'])[1]/preceding::button[1]</value>
      <webElementGuid>96bd9004-a402-4979-aed6-2b584a44263c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='sanjay bug one'])[1]/preceding::button[2]</value>
      <webElementGuid>abfa9e70-a8a7-414a-b7b1-40e46854e73f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='WER-P-0001093']/parent::*</value>
      <webElementGuid>3366020a-9f1d-4f7a-bc76-cbd15cd1e5bd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[10]/div/div/form/button</value>
      <webElementGuid>aceb76ab-a54d-4056-aa6f-47bbbfac16d3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'submit' and (text() = 'WER-P-0001093' or . = 'WER-P-0001093')]</value>
      <webElementGuid>d3348061-da2f-4f44-9aaf-d6754d3cc8aa</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
