<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input__DOB</name>
   <tag></tag>
   <elementGuidId>7f3c7598-0b97-4a0a-8fff-7d7abf41e326</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#dp1686744710522</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='dp1686744710522']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>d7094bd6-8235-43cd-acc0-ef7254c00c24</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>10</value>
      <webElementGuid>c7f1d3d2-1e1e-4f9a-a9ca-6c98ce39e8a8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>minyear</name>
      <type>Main</type>
      <value>1900</value>
      <webElementGuid>e3228c58-631d-48d7-860e-4e6313ec454f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>733bc040-4072-4bd3-a04b-f00e042b32a6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>DOB</value>
      <webElementGuid>d7293c3a-0df0-4d82-bb0a-ce87f79e5c6c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control ui-autocomplete-input ng-pristine ng-untouched ng-isolate-scope hasDatepicker ng-valid-maxlength ng-not-empty ng-valid ng-valid-required</value>
      <webElementGuid>6d95be9d-9670-46c2-9c7c-ddae21111ad9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>DD/MM/YYYY</value>
      <webElementGuid>4ec27f9e-911d-4656-a85c-591fb67f9793</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-model</name>
      <type>Main</type>
      <value>primaryInsured.DOBUI</value>
      <webElementGuid>e4cd077f-bbeb-4410-bab6-9a0e6aafb114</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-change</name>
      <type>Main</type>
      <value>vm.validateDOB(primaryInsured, clientForm.DOB)</value>
      <webElementGuid>11db01b0-ea78-402d-b9a3-cdcd62a3834a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>82fe2b12-63cf-40b2-b6bf-f2988d3369ab</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>dp1686744710522</value>
      <webElementGuid>81734df4-ec98-4b3c-8200-bce2db89b8fb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-invalid</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>89f08689-4653-4d97-b006-6ea2da5c5520</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;dp1686744710522&quot;)</value>
      <webElementGuid>0cefd323-e352-4912-87a2-bee5683d60c0</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='dp1686744710522']</value>
      <webElementGuid>87f5eed0-0fce-4d3d-a98d-204592d90670</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='clientForm']/fieldset/div/ng-container/div[2]/div[2]/div/div[3]/div[2]/div/div/div/input</value>
      <webElementGuid>5a639e87-3605-431d-8c13-ae8034398112</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div[2]/div/div/div/input</value>
      <webElementGuid>72b1d009-8fcc-4ee4-9937-2ccf363e83b9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @name = 'DOB' and @placeholder = 'DD/MM/YYYY' and @id = 'dp1686744710522']</value>
      <webElementGuid>462fe906-aba1-4b72-878a-e1f6eb9e7328</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
