<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Web</name>
   <tag></tag>
   <elementGuidId>474410e0-7c4e-4f01-9492-177354c8d92f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>a.NavAlt-anchor.u-b0</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='ContentPlaceholder1_T53129E6C012_Col00']/nav/div/div[2]/a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>a4d4d56a-e93e-40d9-a282-8688eb62d8a4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>#web</value>
      <webElementGuid>cbb47655-903d-4563-997b-2f9755ebbf45</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>NavAlt-anchor u-b0</value>
      <webElementGuid>39f57fef-ee43-4a08-b896-1cf32bec050e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-label</name>
      <type>Main</type>
      <value>Web content</value>
      <webElementGuid>a3133c95-c0d3-450f-a634-2e6ed41cc0c3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Web</value>
      <webElementGuid>fb106551-1bf7-4177-b502-110e1cb49a39</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ContentPlaceholder1_T53129E6C012_Col00&quot;)/nav[@class=&quot;NavAlt NavAlt--blue u-bn u-tal u-b0&quot;]/div[@class=&quot;container&quot;]/div[2]/a[@class=&quot;NavAlt-anchor u-b0&quot;]</value>
      <webElementGuid>5f83924f-efb6-4151-b5d5-5cbe42009594</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='ContentPlaceholder1_T53129E6C012_Col00']/nav/div/div[2]/a</value>
      <webElementGuid>f7ba1d55-d6d4-4df8-82ab-22a98348fc69</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Web')]</value>
      <webElementGuid>0bb70c11-b0ed-4053-9a7b-0239bf6d8423</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Demos'])[3]/following::a[1]</value>
      <webElementGuid>e0dfe907-ae45-46d7-b0d5-9cd33bbd88ae</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Demos'])[2]/following::a[1]</value>
      <webElementGuid>e887a036-af50-4d47-86ad-bb64db3d8b73</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Desktop'])[2]/preceding::a[1]</value>
      <webElementGuid>527d8d34-6bba-4167-ac95-e415ae015391</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Mobile'])[2]/preceding::a[2]</value>
      <webElementGuid>7e08c506-cbea-40d9-a430-bf84e8c81067</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, '#web')]</value>
      <webElementGuid>0cd74e35-4661-4824-b55f-7ae6a0cb3b1b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//nav/div/div[2]/a</value>
      <webElementGuid>0f1c872f-af3e-48bd-ab9c-db38a736818c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '#web' and (text() = 'Web' or . = 'Web')]</value>
      <webElementGuid>47245d00-f248-4c4c-94bb-d29d9928e9c4</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
