<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Jun 2023 - May 2024</name>
   <tag></tag>
   <elementGuidId>44702895-a6ae-4058-a209-a259ea1a081e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#left-tab7 > ul.nav.nav-tabs > li > a.ng-binding</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='left-tab7']/ul/li/a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>1acbb84e-b11b-4013-b7e0-4ea79076046d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-toggle</name>
      <type>Main</type>
      <value>tab</value>
      <webElementGuid>84e484f3-699b-4759-bf64-5a5166fc6ee9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>#tab1_0</value>
      <webElementGuid>098a8734-c5df-4e8a-af29-a7a2bfb97fee</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ng-binding</value>
      <webElementGuid>4e8aff93-3ca5-4806-a723-df25c91a7df6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Jun 2023 - May 2024</value>
      <webElementGuid>b89c85bc-45a9-40c0-9edc-7ddf8052babd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;left-tab7&quot;)/ul[@class=&quot;nav nav-tabs&quot;]/li[1]/a[@class=&quot;ng-binding&quot;]</value>
      <webElementGuid>402d7558-6dd9-4e16-b2c1-af389479f3f7</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='left-tab7']/ul/li/a</value>
      <webElementGuid>340f0af4-2f33-4120-9dbb-777882fc6e06</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>(//a[contains(text(),'Jun 2023 - May 2024')])[2]</value>
      <webElementGuid>613d050c-65bd-403b-9fc2-833e362e62b1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Action'])[2]/following::a[1]</value>
      <webElementGuid>de2a9e1f-e416-49ba-a663-79dd04f361db</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Attachment'])[1]/following::a[1]</value>
      <webElementGuid>49d137d1-d71d-4650-b8f6-a8d83165577f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Jun 2024 - May 2025'])[2]/preceding::a[1]</value>
      <webElementGuid>939209d0-b629-4b36-bf53-9982d871b903</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Transaction Date'])[1]/preceding::a[2]</value>
      <webElementGuid>fa02c29c-3f69-4742-8e54-55db786a8deb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, '#tab1_0')]</value>
      <webElementGuid>b9fef4f2-8e93-41f1-9854-e0eb450ec5dd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[7]/ul/li/a</value>
      <webElementGuid>601983e6-76c1-42ef-a9e2-ee3f705c5d33</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '#tab1_0' and (text() = 'Jun 2023 - May 2024' or . = 'Jun 2023 - May 2024')]</value>
      <webElementGuid>9b0054f0-557a-4d2c-a85d-6956f03080ac</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
