<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>td_END-WER-Q-0003006</name>
   <tag></tag>
   <elementGuidId>f6991e49-edff-459e-84f3-0c1d81b249be</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='tab1_0']/div/table/tbody/tr[2]/td[2]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>td</value>
      <webElementGuid>07fbcf9e-9aa9-41f5-a0fd-91bc555798bb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ng-binding</value>
      <webElementGuid>18a006ee-abca-42b2-84a0-b2f7326c061e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>END-WER-Q-0003006</value>
      <webElementGuid>25579ab0-ecd4-4158-aec6-cb73a3d9c989</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;tab1_0&quot;)/div[@class=&quot;table-responsive&quot;]/table[@class=&quot;table table-striped table-blue&quot;]/tbody[1]/tr[@class=&quot;ng-scope&quot;]/td[@class=&quot;ng-binding&quot;]</value>
      <webElementGuid>0177d6c5-c3f8-4f73-a165-a3c8fe312228</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='tab1_0']/div/table/tbody/tr[2]/td[2]</value>
      <webElementGuid>99718b73-cf47-42ea-8375-f6fac6881ff7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Policy'])[1]/following::td[2]</value>
      <webElementGuid>223d46aa-7912-47c6-a134-ae1fd9bfd24b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='View'])[3]/following::td[3]</value>
      <webElementGuid>1ecb29ff-1e59-4c81-be38-1c8045addc54</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Endorsement'])[1]/preceding::td[1]</value>
      <webElementGuid>de589c1b-cbdf-4ba4-8e49-87e2c10bf49f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Referred'])[1]/preceding::td[4]</value>
      <webElementGuid>615922fc-99ba-454a-bbb8-f36bb20c5f0c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='END-WER-Q-0003006']/parent::*</value>
      <webElementGuid>a9e8426e-a347-4bcd-bc1e-1afd5ac606b9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[7]/div/div/div/table/tbody/tr[2]/td[2]</value>
      <webElementGuid>104ef51d-7b48-4bc0-9776-4600dd5fe68a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//td[(text() = 'END-WER-Q-0003006' or . = 'END-WER-Q-0003006')]</value>
      <webElementGuid>2e2b6a0b-229f-42fa-a1f6-cdafaaa8f893</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
