<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Operation_calculateButton</name>
   <tag></tag>
   <elementGuidId>390ae1a2-e317-4f7c-8ab7-73bcddd2b7e9</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#calculateButton</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='calculateButton']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>5fc09f2f-c98b-4d0d-90b8-e6a0a3cb9a36</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>4318aefc-80e4-4533-a4ee-dae7a59de205</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn btn-primary</value>
      <webElementGuid>8e80c3b5-5028-448c-985a-c3fdc882e065</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>calculateButton</value>
      <webElementGuid>3f195a77-1298-4bb2-974b-7c04ddc72c80</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>Calculate</value>
      <webElementGuid>12d06065-878f-47b7-8687-d3908323b68e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>calculate()</value>
      <webElementGuid>44e03431-6117-4c11-9d57-386d5e60aa16</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;calculateButton&quot;)</value>
      <webElementGuid>c86d5f97-317a-404e-b73b-eced61617907</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='calculateButton']</value>
      <webElementGuid>3ead8578-b4ee-4362-8066-dd9a7cb306ef</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='calcForm']/div[4]/div[2]/input</value>
      <webElementGuid>e5f1ccc7-f381-4da7-9f95-071c0078ded9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div[2]/input</value>
      <webElementGuid>19d08127-f3c2-40ba-8519-7617f944602c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'button' and @id = 'calculateButton']</value>
      <webElementGuid>4759bf44-a49b-4211-a054-785eeeee20c4</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
