<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_Add                            Subtr_963217</name>
   <tag></tag>
   <elementGuidId>4da9e994-8958-4705-9961-dd91bb11194d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#selectOperationDropdown</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='selectOperationDropdown']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>f14ef21b-a926-4205-85be-a7b546c5f3ac</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>element select medium</value>
      <webElementGuid>38b1135b-eb67-47ca-a56f-b96a2c982454</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>selectOperationDropdown</value>
      <webElementGuid>6674aebf-4850-4652-a686-3a3cdc130307</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>selectOperation</value>
      <webElementGuid>bd48fa82-402e-4ff9-86b7-597ab7bd2461</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onchange</name>
      <type>Main</type>
      <value>operationChanged(this.preset)</value>
      <webElementGuid>071dea93-dcec-4558-9c9c-82ccc8b5372a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value> 
                            Add
                            Subtract
                            Multiply
                            Divide
                            Concatenate
                        </value>
      <webElementGuid>cba2cb9c-a8a7-4aff-a271-3e7d9abd39c2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;selectOperationDropdown&quot;)</value>
      <webElementGuid>a20d44a7-b4e0-47da-a7c5-cde2aabb4589</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='selectOperationDropdown']</value>
      <webElementGuid>11d37cd5-c626-4c90-b35f-869aab5e879f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='calcForm']/div[3]/div[2]/select</value>
      <webElementGuid>99e339bc-62ed-4aec-9306-0686e561e95b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Operation'])[1]/following::select[1]</value>
      <webElementGuid>35479ee6-cf8c-4bfa-8666-adc68ed820d0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Second number'])[1]/following::select[1]</value>
      <webElementGuid>3e9e4786-1a8d-4873-a331-c1c9065cc6f3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Calculating ...'])[1]/preceding::select[1]</value>
      <webElementGuid>93dce64b-7a4c-4d98-b3df-90b77c159139</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Answer'])[1]/preceding::select[1]</value>
      <webElementGuid>02a58892-c89e-4d18-a802-ff71a4fb317d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div[2]/select</value>
      <webElementGuid>193aa471-ae2b-4a36-b6c8-7b4f230cb375</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@id = 'selectOperationDropdown' and @name = 'selectOperation' and (text() = ' 
                            Add
                            Subtract
                            Multiply
                            Divide
                            Concatenate
                        ' or . = ' 
                            Add
                            Subtract
                            Multiply
                            Divide
                            Concatenate
                        ')]</value>
      <webElementGuid>3cc2cb93-da47-4e6d-bae3-3ca52bf69b4a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
