<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_I like XBOX_009</name>
   <tag></tag>
   <elementGuidId>66459fed-d839-4b4e-939d-753e4cbb0a33</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>input[name=&quot;009&quot;]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@name='009']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>c7fb3771-da17-45ff-be29-c1d515d29679</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>radio</value>
      <webElementGuid>d8b67ecd-64fc-46dc-bd17-5193235205da</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-model</name>
      <type>Main</type>
      <value>formData.type</value>
      <webElementGuid>0881e402-ffd4-40d0-be25-16303419ce25</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>xbox</value>
      <webElementGuid>cedee133-16de-4205-9f9b-e17c2e8038d0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ng-pristine ng-valid</value>
      <webElementGuid>21a80e7d-bbd4-46f1-9f4e-c95b17f2a466</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>009</value>
      <webElementGuid>66e8c813-8135-4074-8c06-69db0c5c46cc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;form-views&quot;)/div[@class=&quot;form-group ng-scope&quot;]/div[@class=&quot;radio&quot;]/label[1]/input[@class=&quot;ng-pristine ng-valid&quot;]</value>
      <webElementGuid>44ff3091-e3e6-4996-a7f2-50c2254b67a8</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@name='009']</value>
      <webElementGuid>8cc6fa4c-ff6d-4ea5-bdfc-b058fcb906d3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='form-views']/div/div/label/input</value>
      <webElementGuid>87790e98-fc6c-4c63-9656-14840e88acbb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input</value>
      <webElementGuid>3984d1bb-273b-4a0d-a2b8-a09985397b90</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'radio' and @name = '009']</value>
      <webElementGuid>5d35ee72-a82e-4c58-b2dd-4265ff6c138b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
