<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Next Section_glyphicon glyphicon-circl_68c672</name>
   <tag></tag>
   <elementGuidId>2b34101a-5995-4b48-b2fa-a0edfdd1d756</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>span.glyphicon.glyphicon-circle-arrow-right</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='form-views']/div[3]/div/a/span</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>000b8e5b-b9ac-49c0-97b8-03c023bfacde</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>glyphicon glyphicon-circle-arrow-right</value>
      <webElementGuid>6c2a7225-24d8-4199-9cfc-350acf69fdf2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;form-views&quot;)/div[@class=&quot;form-group row ng-scope&quot;]/div[@class=&quot;col-xs-6 col-xs-offset-3&quot;]/a[@class=&quot;btn btn-block btn-info&quot;]/span[@class=&quot;glyphicon glyphicon-circle-arrow-right&quot;]</value>
      <webElementGuid>9db2333f-f506-4764-99a0-0af7fec090ca</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='form-views']/div[3]/div/a/span</value>
      <webElementGuid>d00436ac-6530-4bc5-9ed2-7394ab2e6f60</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/a/span</value>
      <webElementGuid>55c257a5-8f44-482a-b566-5c118a99845c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
