<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Client Management</name>
   <tag></tag>
   <elementGuidId>d1566318-5096-4856-8a2a-520b12a0bf71</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>li:nth-of-type(3) > a.has-ul</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='sidebarMenu']/div/ul/li[3]/a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>4bae4cc5-5676-436c-8f68-ee1832fd7a2e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>#</value>
      <webElementGuid>5a57d21f-3f9e-475d-9b76-9f7f698ad33d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>has-ul</value>
      <webElementGuid>116992b7-ed03-47f5-8d10-47f35d69c3bd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value> Client Management</value>
      <webElementGuid>8bf93b89-5900-4df7-9ea5-3b92e73caefa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;sidebarMenu&quot;)/div[@class=&quot;sidebar-content&quot;]/ul[@class=&quot;navigation navigation-main navigation-accordion&quot;]/li[3]/a[@class=&quot;has-ul&quot;]</value>
      <webElementGuid>b493fac0-5823-492a-9448-cac50d58f53a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='sidebarMenu']/div/ul/li[3]/a</value>
      <webElementGuid>47d7c8da-e763-493b-8a17-2ea2575c7875</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Add New User'])[1]/following::a[1]</value>
      <webElementGuid>daab34c0-f8a9-42f7-adc9-811c2e3eac8b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Search User'])[1]/following::a[2]</value>
      <webElementGuid>61f65ef6-2b0a-46fe-bfad-d13d199b8067</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Search Client'])[1]/preceding::a[1]</value>
      <webElementGuid>1f775f52-c715-4590-b0ed-e1ba65d32cee</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>(//a[contains(@href, '#')])[5]</value>
      <webElementGuid>6f65fefa-22ac-465a-9e27-461f7907222a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/ul/li[3]/a</value>
      <webElementGuid>76485476-28b3-45ea-b4a9-144cb71d38fc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '#' and (text() = ' Client Management' or . = ' Client Management')]</value>
      <webElementGuid>a9be5660-c618-4065-bcd0-091460d536d8</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
