<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input__firstName</name>
   <tag></tag>
   <elementGuidId>f40f0ccc-5268-4ca7-aa58-b1881388e10e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>input[name=&quot;firstName&quot;]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@name='firstName']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>f64f71b6-7503-48a4-8dc0-1441558689db</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>firstName</value>
      <webElementGuid>d6a74e46-b1f3-443b-bf3d-7eea29147092</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>2dea8a88-1a79-41e8-a529-ac53a92a12e5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control field-md ng-pristine ng-untouched ng-empty ng-invalid ng-invalid-required ng-valid-minlength ng-valid-maxlength</value>
      <webElementGuid>2dc2f8fe-005c-4a21-b973-12b336bde004</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-model</name>
      <type>Main</type>
      <value>primaryInsured.FirstName</value>
      <webElementGuid>2b9ae29a-dde9-4905-9222-c9ba4c1d9f4a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-minlength</name>
      <type>Main</type>
      <value>3</value>
      <webElementGuid>c5cb0efb-7447-4f25-a5cc-5a86bdc19532</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-maxlength</name>
      <type>Main</type>
      <value>20</value>
      <webElementGuid>13bb03ed-be65-4c4b-a146-a2568baab7d4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>8ac137ae-57d8-46fc-a002-54a808247855</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-invalid</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>36edc55c-8eec-44e7-b6d9-0db86cd8f95c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;clientForm&quot;)/fieldset[1]/div[@class=&quot;panel panel-body no-header&quot;]/ng-container[1]/div[@class=&quot;panel sub-panel primary-insured-individual&quot;]/div[@class=&quot;panel-body&quot;]/div[@class=&quot;form-body&quot;]/div[@class=&quot;row ng-scope&quot;]/div[@class=&quot;col-sm-12 col-lg-6&quot;]/div[@class=&quot;row form-group clearfix&quot;]/div[@class=&quot;col-sm-8 col-lg-8&quot;]/input[@class=&quot;form-control field-md ng-pristine ng-untouched ng-empty ng-invalid ng-invalid-required ng-valid-minlength ng-valid-maxlength&quot;]</value>
      <webElementGuid>7b86de56-0ba6-485e-8783-2d3558c79364</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@name='firstName']</value>
      <webElementGuid>efe9dbce-fe69-45d1-bc86-f81a9b28f17b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='clientForm']/fieldset/div/ng-container/div[2]/div[2]/div/div[2]/div/div/div/input</value>
      <webElementGuid>4620276a-8907-4406-8cd2-9dd04fc815cf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/div/input</value>
      <webElementGuid>8b691b66-e0be-4d65-bfeb-ff27008f8bef</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@name = 'firstName' and @type = 'text']</value>
      <webElementGuid>688afc36-db33-410e-8201-33b71c458b8b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
