<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input__DOB</name>
   <tag></tag>
   <elementGuidId>b55278a2-fff9-43d6-9249-cb0b8a3d6728</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#dp1686664750478</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='dp1686664750478']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>ab3de28b-8c55-47d3-9c38-b888b124c315</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>10</value>
      <webElementGuid>71d2407d-d5d9-430f-ae53-99a9b83cae12</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>minyear</name>
      <type>Main</type>
      <value>1900</value>
      <webElementGuid>d0c9df78-9c1b-4766-9f36-af08f0400b68</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>d74dc75a-6c1b-44c4-b12b-1b0ed61af49f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>DOB</value>
      <webElementGuid>f6ca6221-89bd-4362-bd53-7805c278a7ad</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control ui-autocomplete-input ng-pristine ng-untouched ng-isolate-scope hasDatepicker ng-empty ng-invalid ng-invalid-required ng-valid-maxlength</value>
      <webElementGuid>40a93dbe-bc13-416d-878b-845ab09a1057</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>DD/MM/YYYY</value>
      <webElementGuid>fa53771f-dece-49cd-8551-7e38ad2d66f4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-model</name>
      <type>Main</type>
      <value>primaryInsured.DOBUI</value>
      <webElementGuid>a7b83d6d-ee90-4687-8a1d-236024fa30bf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-change</name>
      <type>Main</type>
      <value>vm.validateDOB(primaryInsured, clientForm.DOB)</value>
      <webElementGuid>a8e69720-2352-4f2c-a0f3-f29e99a537de</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>7ff415fe-6a6e-4e76-9048-f2060b2d9e09</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>dp1686664750478</value>
      <webElementGuid>8957082b-9216-475a-a0c7-0e05d31b3680</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-invalid</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>7c039853-17a3-44a1-b576-fa7ee90e568a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;dp1686664750478&quot;)</value>
      <webElementGuid>6f728fe0-5ed0-46f5-98a2-53572ea57ae9</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='dp1686664750478']</value>
      <webElementGuid>bf0bec0a-4697-40ef-a6a9-e3435ed2013a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='clientForm']/fieldset/div/ng-container/div[2]/div[2]/div/div[3]/div[2]/div/div/div/input</value>
      <webElementGuid>233e701c-9c78-44af-91b2-b64669859880</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div[2]/div/div/div/input</value>
      <webElementGuid>05a1e9ab-e7ec-4544-a6cb-061c02e73b54</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @name = 'DOB' and @placeholder = 'DD/MM/YYYY' and @id = 'dp1686664750478']</value>
      <webElementGuid>bd1d2864-83e1-4f92-870d-06bfb03c7f49</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
