<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input__autocomplete</name>
   <tag></tag>
   <elementGuidId>8aa5efa2-9745-4f32-8f36-c81bc7b18d9f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#input-0</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='input-0']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>31b2c46b-ab44-460b-a217-741d32755808</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>search</value>
      <webElementGuid>5f702509-735e-4024-97da-b1e665c9311d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>input-0</value>
      <webElementGuid>a64f55da-fbb3-4265-a1e1-1e594f1553de</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>autocomplete</value>
      <webElementGuid>6132c07f-e275-44c7-8765-0b533090567a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-class</name>
      <type>Main</type>
      <value>::inputClass</value>
      <webElementGuid>b08c5138-bf67-4609-a897-3e7dd75bb81b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-if</name>
      <type>Main</type>
      <value>!floatingLabel</value>
      <webElementGuid>6dc72193-bcec-4b4f-9e2c-7c35079670be</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>e5b317f4-019a-437a-af51-a6fe347141be</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-required</name>
      <type>Main</type>
      <value>$mdAutocompleteCtrl.isRequired</value>
      <webElementGuid>3b6d2716-04d4-48e3-96fc-edc3bdce3c26</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-disabled</name>
      <type>Main</type>
      <value>$mdAutocompleteCtrl.isDisabled</value>
      <webElementGuid>0193987a-e4b8-44d1-a572-0ce6c44f74dc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-readonly</name>
      <type>Main</type>
      <value>$mdAutocompleteCtrl.isReadonly</value>
      <webElementGuid>c43d270d-5311-47e4-b615-7336fe430ee1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-model</name>
      <type>Main</type>
      <value>$mdAutocompleteCtrl.scope.searchText</value>
      <webElementGuid>a15e37ba-c97f-44b5-bb78-69d1d3ff8d85</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-keydown</name>
      <type>Main</type>
      <value>$mdAutocompleteCtrl.keydown($event)</value>
      <webElementGuid>bd85fd0e-98b8-4edf-a344-54a9782c1451</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-blur</name>
      <type>Main</type>
      <value>$mdAutocompleteCtrl.blur($event)</value>
      <webElementGuid>e0002230-a9cd-4a73-87f8-0d92713ad0cd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-focus</name>
      <type>Main</type>
      <value>$mdAutocompleteCtrl.focus($event)</value>
      <webElementGuid>feecab39-00ce-4883-83ad-2ad74061617d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-autocomplete</name>
      <type>Main</type>
      <value>list</value>
      <webElementGuid>f148d16c-a8bc-49ee-9267-3a0f616dcba5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>combobox</value>
      <webElementGuid>99363994-b815-4a15-ae29-4f2ae45cfe1c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-haspopup</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>02cef418-85dc-4eff-aa89-75c17c10d4bc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-expanded</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>58dfac38-a2c9-44c7-9909-f3c81f1d85b3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-owns</name>
      <type>Main</type>
      <value>ul-0</value>
      <webElementGuid>a4c4f1ef-1a45-4fc7-8cb8-323578d5a869</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-attr-aria-activedescendant</name>
      <type>Main</type>
      <value>{{$mdAutocompleteCtrl.index >= 0 ? 'selected_option' : undefined}}</value>
      <webElementGuid>4ed512a5-faa6-431c-8667-0effcc0e0390</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ng-pristine ng-untouched ng-scope ng-empty ng-invalid ng-invalid-required ng-valid-minlength ng-valid-maxlength ng-not-empty-add ng-pristine-remove ng-dirty-add ng-valid-parse-add ng-valid-add ng-invalid-remove ng-valid-required-add ng-invalid-required-remove ng-animate ng-empty-remove</value>
      <webElementGuid>08a1b6f7-13fe-432c-a4dc-bf6b5a89e7f5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>required</name>
      <type>Main</type>
      <value>required</value>
      <webElementGuid>146c1901-d7ab-447b-8912-f1c71c3bd359</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-invalid</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>86fd51e1-f763-4af4-991f-9cf8af0f7556</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-ng-animate</name>
      <type>Main</type>
      <value>2</value>
      <webElementGuid>9f9d6d77-2429-4799-892d-3ff8b6e094e1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;input-0&quot;)</value>
      <webElementGuid>5ea46be7-b849-4154-8d96-5d128e114bae</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='input-0']</value>
      <webElementGuid>a4dfe023-9f1c-4d7e-a447-afefbffc5f63</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='clientForm']/fieldset/div/div[2]/div[2]/div/div/div/div/div/div/searchaddress/md-autocomplete/md-autocomplete-wrap/input</value>
      <webElementGuid>0f80c36c-752a-4129-b9ff-a4f3e05fd7f6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//md-autocomplete-wrap/input</value>
      <webElementGuid>68403691-9e52-44fb-9446-40791f5d2781</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'search' and @id = 'input-0' and @name = 'autocomplete']</value>
      <webElementGuid>2550737a-af8e-4182-844e-7b273509feac</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
