<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_Select                              _534643</name>
   <tag></tag>
   <elementGuidId>14fd49e3-d3ff-4f3a-93ee-7fb71d5fa977</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>select[name=&quot;prefix&quot;]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//select[@name='prefix']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>f0909d49-08c9-4197-aa23-575fe74f8279</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>prefix</value>
      <webElementGuid>acc87b2d-9726-4bda-bd93-29a3cf951c0a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-model</name>
      <type>Main</type>
      <value>primaryInsured.Prefix</value>
      <webElementGuid>83eb19fb-4600-41e8-9416-d605dc0bf75d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control field-md ng-pristine ng-untouched ng-empty ng-invalid ng-invalid-required</value>
      <webElementGuid>8e61e731-d275-40e4-b7c6-36bcf7cf18c6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-change</name>
      <type>Main</type>
      <value>vm.changeOther(primaryInsured.Prefix, 'PrimaryInsured')</value>
      <webElementGuid>415a6fbc-97a7-4749-bbc4-ebffd49a6518</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-invalid</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>6b9774e0-0319-4f65-b7de-c7fc7e5c1677</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
                                                    Select
                                                    DrMissMrMrsMsOther
                                                </value>
      <webElementGuid>0680aa0c-472a-4341-a15e-46592bc14005</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;clientForm&quot;)/fieldset[1]/div[@class=&quot;panel panel-body no-header&quot;]/ng-container[1]/div[@class=&quot;panel sub-panel primary-insured-individual&quot;]/div[@class=&quot;panel-body&quot;]/div[@class=&quot;form-body&quot;]/div[@class=&quot;row prefixRow ng-scope&quot;]/div[@class=&quot;col-sm-12 col-lg-6&quot;]/div[@class=&quot;row form-group clearfix&quot;]/div[@class=&quot;col-sm-8 col-lg-8&quot;]/select[@class=&quot;form-control field-md ng-pristine ng-untouched ng-empty ng-invalid ng-invalid-required&quot;]</value>
      <webElementGuid>1771b158-b666-484f-8a2f-ee66710f35e4</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@name='prefix']</value>
      <webElementGuid>4e4962cf-b7a4-4f92-9073-2f294a91f8a0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='clientForm']/fieldset/div/ng-container/div[2]/div[2]/div/div/div/div/div/select</value>
      <webElementGuid>007077e4-6e5a-42f1-9c6d-5eae9a2069d5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='*'])[2]/following::select[1]</value>
      <webElementGuid>d3195e72-843a-4ff6-a26c-4c23f692a913</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='*'])[3]/preceding::select[1]</value>
      <webElementGuid>df7c9278-0e2f-43b2-b3b8-c8c0040074b7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div/div/div/div/select</value>
      <webElementGuid>1bb53d5f-00dc-48b5-abc2-168a8afb542b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@name = 'prefix' and (text() = '
                                                    Select
                                                    DrMissMrMrsMsOther
                                                ' or . = '
                                                    Select
                                                    DrMissMrMrsMsOther
                                                ')]</value>
      <webElementGuid>36d630e3-0ad5-40bc-914f-cd95de203341</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
