<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Automation Tools_tool_1</name>
   <tag></tag>
   <elementGuidId>baa1efe9-26ad-472f-b640-799ade4db139</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#tool-1</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='tool-1']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>fab5f3e4-ac86-40d5-8f1a-a907d3ad01bc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>tool-1</value>
      <webElementGuid>95e3aeb5-c528-451e-b18e-c5b57d088312</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>tool</value>
      <webElementGuid>14e1ea13-8322-4bc2-886b-da82da7234a1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>checkbox</value>
      <webElementGuid>f5796d94-e552-479f-9e2e-f5c4fd51f48c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>Selenium IDE</value>
      <webElementGuid>ba82d001-f927-40ca-a145-935ba36a41a8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;tool-1&quot;)</value>
      <webElementGuid>3ad61e1c-5d02-446f-ad77-d692772d6f3f</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='tool-1']</value>
      <webElementGuid>004b5733-02df-4545-bc48-a7643b5f57cd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='post-body-3077692503353518311']/div/div/div/h2[2]/div/div/div[22]/input[2]</value>
      <webElementGuid>b8b7271e-e705-460a-bbde-3dd483381782</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[22]/input[2]</value>
      <webElementGuid>5d65cefa-9a15-415a-b8d7-1221d2749e11</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'tool-1' and @name = 'tool' and @type = 'checkbox']</value>
      <webElementGuid>c40207dd-1734-4647-b01b-4bfe44967cde</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
