<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Gender_sex</name>
   <tag></tag>
   <elementGuidId>4c35251b-f008-4a03-8bce-37b30efb9d5c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#sex-0</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='sex-0']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>89ac8d64-09c7-4816-ada1-1462e833ab28</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>sex-0</value>
      <webElementGuid>f5057a84-4c86-4758-8afc-a8184eab06f2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>sex</value>
      <webElementGuid>4e3600f2-4a6a-4e09-908c-86a3bf307201</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>radio</value>
      <webElementGuid>869a1d0e-adc1-44ba-aadf-efffe2b68c0c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>Male</value>
      <webElementGuid>25818314-4342-4660-b88d-a0630a58cc70</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;sex-0&quot;)</value>
      <webElementGuid>1ba9a673-b6d0-4beb-bc9a-70b8fe3059bc</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='sex-0']</value>
      <webElementGuid>aa1b2e06-4036-4ea8-9b5d-df219b389d94</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='post-body-3077692503353518311']/div/div/div/h2[2]/div/div/div[9]/input</value>
      <webElementGuid>e19d7d94-326d-4cd5-a3d0-d951a8dcfa79</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[9]/input</value>
      <webElementGuid>25e93471-137b-4a05-91c4-b1ce32dac861</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'sex-0' and @name = 'sex' and @type = 'radio']</value>
      <webElementGuid>21544eb9-f05a-4c21-9180-9ad11f2e4ab5</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
