<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Bag_desktop-searchBar</name>
   <tag></tag>
   <elementGuidId>de8eda80-4577-4805-9e24-15892a1e0aaf</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>input.desktop-searchBar</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@value='']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>ae738309-ae56-42a4-b27e-0d99eb47f065</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Search for products, brands and more</value>
      <webElementGuid>d63f513b-2b42-44c3-b8a5-05911cfec65c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>desktop-searchBar</value>
      <webElementGuid>ea8c044c-ad43-4c72-93d1-2c27cb37219e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-reactid</name>
      <type>Main</type>
      <value>907</value>
      <webElementGuid>ab0cbe3c-b6c2-43a3-a4db-1468949ac721</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;desktop-header-cnt&quot;)/div[@class=&quot;desktop-bound&quot;]/div[@class=&quot;desktop-query&quot;]/input[@class=&quot;desktop-searchBar&quot;]</value>
      <webElementGuid>aead4d00-af12-411d-976b-9209ed010ca2</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@value='']</value>
      <webElementGuid>6678ad89-0e6d-4ae3-b53e-96534301e657</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//header[@id='desktop-header-cnt']/div[2]/div[3]/input</value>
      <webElementGuid>dbdd8ac7-af17-4728-8135-08a5bd72e545</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input</value>
      <webElementGuid>7fc8f4cc-0cfd-4a72-a513-71356d9a616d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@placeholder = 'Search for products, brands and more']</value>
      <webElementGuid>916cb842-0be0-49eb-8341-fd35bf98b1d6</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
