<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>li_Men Casual Shoes</name>
   <tag></tag>
   <elementGuidId>45ac08b6-3cb4-4a82-9b4a-91875c57ff19</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>li.desktop-suggestion.null</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//header[@id='desktop-header-cnt']/div[2]/div[3]/div/ul/li[2]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>li</value>
      <webElementGuid>e88e7aab-341e-4718-b8f8-f089ffd869e0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>desktop-suggestion null</value>
      <webElementGuid>8c21a1d4-c96b-4763-9d1e-37a7868c1b71</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-index</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>63509be9-fc90-48f5-9bac-a80822a681d5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-activeindex</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>b2a608cb-6ccc-4511-8b11-d7bec8c17a7e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-count</name>
      <type>Main</type>
      <value>20865</value>
      <webElementGuid>93ecaa57-532e-4da8-8564-4d472d8d0e19</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-value</name>
      <type>Main</type>
      <value>/men-casual-shoes?extra_search_param=isautosuggestentry%3atrue%3a%3aid%3a2297-men-casual-shoes</value>
      <webElementGuid>5cb78945-ac18-41c5-9edd-e5134ebc947e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Men Casual Shoes</value>
      <webElementGuid>c53840a2-a464-4e8c-87a0-67c8de081099</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;desktop-header-cnt&quot;)/div[@class=&quot;desktop-bound&quot;]/div[@class=&quot;desktop-query&quot;]/div[@class=&quot;desktop-autoSuggest desktop-showContent&quot;]/ul[@class=&quot;desktop-group&quot;]/li[@class=&quot;desktop-suggestion null&quot;]</value>
      <webElementGuid>2c748870-b33a-4936-adc3-171480d94293</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//header[@id='desktop-header-cnt']/div[2]/div[3]/div/ul/li[2]</value>
      <webElementGuid>00dc369f-7b9b-4d55-bf35-e87b1e14bf03</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Bag'])[1]/following::li[2]</value>
      <webElementGuid>3f096ef1-9450-46e2-85a6-8b72e5cf06f1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Men Casual Trousers'])[1]/preceding::li[1]</value>
      <webElementGuid>5cf02393-633c-4a96-ad2e-7289a1cbb231</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Men Casual Shirts'])[1]/preceding::li[2]</value>
      <webElementGuid>f69791da-41d4-4dee-8f51-6893cebd6da7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Men Casual Shoes']/parent::*</value>
      <webElementGuid>334cea99-da12-4cb3-b895-9db044ccfd8b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/ul/li[2]</value>
      <webElementGuid>87ff9530-3d2e-4ef1-997e-1e41576ebada</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//li[(text() = 'Men Casual Shoes' or . = 'Men Casual Shoes')]</value>
      <webElementGuid>3d474fcd-334c-496a-b4ed-80b840a7611a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
