<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>iframe_concat(id(, , hubspot-conversations-_2102a2</name>
   <tag></tag>
   <elementGuidId>e86085ab-52b1-4317-8f85-769ebcac9d0b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#hubspot-conversations-iframe</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//iframe[@id='hubspot-conversations-iframe']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>iframe</value>
      <webElementGuid>8cc4e3b1-10ac-40bb-8fd8-90769f13fcba</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://app.hubspot.com/conversations-visitor/6856823/threads/utk/dccf763ec704411188c9a4a678fe78a9?uuid=fc6e6061bdff48ddbd3022f533ccc5cb&amp;mobile=false&amp;mobileSafari=false&amp;hideWelcomeMessage=false&amp;hstc=null&amp;domain=phptravels.com&amp;inApp53=false&amp;messagesUtk=dccf763ec704411188c9a4a678fe78a9&amp;url=https%3A%2F%2Fphptravels.com%2Fdemo%2F&amp;inline=false&amp;isFullscreen=false&amp;globalCookieOptOut=null&amp;isFirstVisitorSession=true&amp;isAttachmentDisabled=false&amp;enableWidgetCookieBanner=false&amp;isInCMS=false</value>
      <webElementGuid>85dd3629-23b4-48a0-b6d1-d21fae4d43d9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>hubspot-conversations-iframe</value>
      <webElementGuid>6a73f6c6-a37d-4a75-9c7b-aa0da6ae45b1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>region</value>
      <webElementGuid>1e1e3ab9-d0dd-49a1-852d-9f12c896a98e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-label</name>
      <type>Main</type>
      <value>Chat Widget</value>
      <webElementGuid>0170cc1f-c459-4afd-9344-b2b8c4576454</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-test-id</name>
      <type>Main</type>
      <value>chat-widget-iframe</value>
      <webElementGuid>722ba31a-f102-4922-bfb0-9f453bc4f3e6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;hubspot-conversations-iframe&quot;)</value>
      <webElementGuid>928c6f07-b6d5-401e-a758-6e170d2ce7dc</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//iframe[@id='hubspot-conversations-iframe']</value>
      <webElementGuid>1692ed2a-4fa7-42aa-96b1-edb170d43b32</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='hubspot-messages-iframe-container']/iframe</value>
      <webElementGuid>d93fb67a-1fc6-4ad5-b9d7-d68448659098</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/iframe</value>
      <webElementGuid>bc269ff6-1655-4364-a253-d393e05ce8d9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//iframe[@src = 'https://app.hubspot.com/conversations-visitor/6856823/threads/utk/dccf763ec704411188c9a4a678fe78a9?uuid=fc6e6061bdff48ddbd3022f533ccc5cb&amp;mobile=false&amp;mobileSafari=false&amp;hideWelcomeMessage=false&amp;hstc=null&amp;domain=phptravels.com&amp;inApp53=false&amp;messagesUtk=dccf763ec704411188c9a4a678fe78a9&amp;url=https%3A%2F%2Fphptravels.com%2Fdemo%2F&amp;inline=false&amp;isFullscreen=false&amp;globalCookieOptOut=null&amp;isFirstVisitorSession=true&amp;isAttachmentDisabled=false&amp;enableWidgetCookieBanner=false&amp;isInCMS=false' and @id = 'hubspot-conversations-iframe']</value>
      <webElementGuid>7af67fd4-8fc2-4b50-b47a-ec75fad4e894</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
