<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>svg</name>
   <tag></tag>
   <elementGuidId>f9dcb0f1-6140-49b8-8a8e-1288a35497ba</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>svg</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>svg</value>
      <webElementGuid>4e9d26a1-697b-4aba-abdd-a11a85ebb598</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>width</name>
      <type>Main</type>
      <value>1em</value>
      <webElementGuid>da16257f-f53e-4ad2-a400-50e873cf006f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>height</name>
      <type>Main</type>
      <value>1em</value>
      <webElementGuid>a10e60b9-14f7-45c3-b7b9-506f08a5e20d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>viewBox</name>
      <type>Main</type>
      <value>0 0 24 24</value>
      <webElementGuid>147a0826-2cf4-4b87-a3ad-034ed130745c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xmlns</name>
      <type>Main</type>
      <value>http://www.w3.org/2000/svg</value>
      <webElementGuid>1fc5e85b-eecd-4cd8-8999-bdf3431d7614</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xmlns:xlink</name>
      <type>Main</type>
      <value>http://www.w3.org/1999/xlink</value>
      <webElementGuid>9db3a4d9-a09a-4398-b7e4-e989e6c674f7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[@class=&quot;lang-en&quot;]/body[@class=&quot;hubspot messages-body&quot;]/div[@class=&quot;widget&quot;]/div[1]/div[@class=&quot;Application__WidgetAppContainer-sc-1f2l0a1-0 dvBAhE widget-app-container&quot;]/span[2]/div[@class=&quot;InitialMessageBubble__StyleWrapper-sc-1k5uzbp-0 dKicdm&quot;]/button[@class=&quot;VizExIconButton__AbstractVizExIconButton-sc-1aehz68-0 klHCMC InitialMessageBubble__CloseButton-sc-1k5uzbp-1 jlUFRn&quot;]/div[@class=&quot;VizExIcon__IconWrapper-sc-1eefe0y-0 mIPnt&quot;]/svg[1]</value>
      <webElementGuid>1fe5a451-89e5-4093-9f3c-4d7bfae4639e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/phptravels/Page_Book Your Free Demo Now - Phptravels/iframe_concat(id(, , hubspot-conversations-_2102a2</value>
      <webElementGuid>aca27fb3-ec53-469b-9719-7c693819cf33</webElementGuid>
   </webElementProperties>
</WebElementEntity>
