<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Know More_autocomplete-input</name>
   <tag></tag>
   <elementGuidId>afb12a32-7aad-4505-bdd0-60900e2babd5</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#autocomplete-input</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='autocomplete-input']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>142c97e8-a031-4cbe-b51b-efd632947bef</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>autocomplete-input</value>
      <webElementGuid>84b058b4-e69d-4490-8795-aaf6854a50bd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>ecd9ecd5-6416-481a-92f7-5f9152902118</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>custom-delivery-textbox_deliveryInputField__10gjM custom-delivery-textbox_animate__34HSc </value>
      <webElementGuid>6ae33bd3-789b-4964-a1c2-4ba957400e6b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>* Enter Pincode, Location or Area</value>
      <webElementGuid>4ffd4d27-087c-4c64-bc72-af34edb03d3d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Start typing and select from suggestions</value>
      <webElementGuid>2e60cbbf-3e49-4794-8182-ad46c97b880c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;autocomplete-input&quot;)</value>
      <webElementGuid>61b6a44d-1c35-431c-89f3-159f81836d64</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='autocomplete-input']</value>
      <webElementGuid>9ee0b166-2ca8-48c9-ab0d-62d9a74b59fb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='pincode-input']/div/div/input</value>
      <webElementGuid>b5bd7e47-5c43-42ce-91bd-1a47d32faf54</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[8]/div/div/div/div/input</value>
      <webElementGuid>d2a0412b-4389-4045-950a-248eb8fc3b30</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'autocomplete-input' and @type = 'text' and @placeholder = '* Enter Pincode, Location or Area' and @title = 'Start typing and select from suggestions']</value>
      <webElementGuid>0600cd91-13a4-4425-9c24-ce7c351ba126</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
