<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_INDIE</name>
   <tag></tag>
   <elementGuidId>6d001f2d-3ac9-43bc-8248-9140b43acc77</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='appContainer']/div/div/header/div[3]/div/ul/li[4]/a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>df02178a-bb5f-4051-b50c-b66aded55423</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/shop/indie</value>
      <webElementGuid>17635c58-2687-498a-a86c-512a8e289998</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>INDIE</value>
      <webElementGuid>e77de23e-67b2-464a-9fa0-9818704c513a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value> alignTag</value>
      <webElementGuid>558ed3f9-b0f1-4bdf-b28e-4b325f86c461</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>INDIE</value>
      <webElementGuid>82b7f60a-6985-43aa-b576-e8342eed49bf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;appContainer&quot;)/div[@class=&quot;false header-wrapper&quot;]/div[@class=&quot;main-header dodShadow&quot;]/header[1]/div[@class=&quot;header-right&quot;]/div[@class=&quot;menu-newlist&quot;]/ul[@class=&quot;level-first false&quot;]/li[4]/a[@class=&quot;alignTag&quot;]</value>
      <webElementGuid>33f1f333-2af6-4afe-b917-7b2e2000c4b6</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='appContainer']/div/div/header/div[3]/div/ul/li[4]/a</value>
      <webElementGuid>58c7fdbf-daf4-431e-ba01-57837d136b32</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'INDIE')]</value>
      <webElementGuid>486b05d4-2cd1-4d19-925c-f9b1098c71e0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Lee Cooper'])[2]/following::a[1]</value>
      <webElementGuid>00dd6d51-15b6-4153-ac45-0b7681ab18ac</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='MUJI'])[1]/following::a[2]</value>
      <webElementGuid>7b8323d6-3fc5-4889-b96c-7870860a8beb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Shop by:'])[4]/preceding::a[1]</value>
      <webElementGuid>5d3bfa3f-86a1-48a1-91ef-cf7586b27709</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='CATEGORIES'])[4]/preceding::a[1]</value>
      <webElementGuid>effbc178-057d-4ea2-b74f-656bf22f7a69</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='INDIE']/parent::*</value>
      <webElementGuid>660fa625-bee4-462c-a3e7-9f7a9b1969bb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, '/shop/indie')]</value>
      <webElementGuid>c82e2090-f556-473f-8be4-fb053f6d9ecf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[4]/a</value>
      <webElementGuid>45b49ddb-ff9b-4a0e-8082-2d41bc38f9b5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '/shop/indie' and @title = 'INDIE' and (text() = 'INDIE' or . = 'INDIE')]</value>
      <webElementGuid>65498564-1387-47f3-833d-96a37978172d</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
