<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img__rilrtl-lazy-img  rilrtl-lazy-img-loaded</name>
   <tag></tag>
   <elementGuidId>35d798c7-c07c-4f04-80cf-87ca909d0a76</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.465738270001 > img.rilrtl-lazy-img.rilrtl-lazy-img-loaded</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='products']/div[3]/div/div/div[2]/a/div/div/div/img</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>d0708f88-b0de-459a-b080-73ee0e70a0ac</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>rilrtl-lazy-img  rilrtl-lazy-img-loaded</value>
      <webElementGuid>0a26fb66-7ab3-44e4-ae72-84e78936ed13</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://assets.ajio.com/medias/sys_master/root/20230321/HAHB/64195210f997dde6f41b1607/puma_black_low-tops_lace-up_sports_shoes.jpg</value>
      <webElementGuid>490c9a0e-f9c7-4e31-9ed3-c53ccbfe804b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;products&quot;)/div[@class=&quot;items&quot;]/div[@class=&quot;ReactVirtualized__Grid items&quot;]/div[@class=&quot;ReactVirtualized__Grid__innerScrollContainer&quot;]/div[@class=&quot;item rilrtl-products-list__item item&quot;]/a[@class=&quot;rilrtl-products-list__link&quot;]/div[@class=&quot;preview&quot;]/div[@class=&quot;imgHolder&quot;]/div[@class=&quot;465738270001&quot;]/img[@class=&quot;rilrtl-lazy-img  rilrtl-lazy-img-loaded&quot;]</value>
      <webElementGuid>e7542f7d-a4d8-409e-9cec-c0561435d8bf</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='products']/div[3]/div/div/div[2]/a/div/div/div/img</value>
      <webElementGuid>3ac82762-369a-4c55-99fd-c21d8f66871d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>//img[contains(@src,'https://assets.ajio.com/medias/sys_master/root/20230321/HAHB/64195210f997dde6f41b1607/puma_black_low-tops_lace-up_sports_shoes.jpg')]</value>
      <webElementGuid>6d73622c-d73f-4d5e-9aeb-dfa5fd97d29e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/a/div/div/div/img</value>
      <webElementGuid>dae76be1-d023-45b9-ad17-ec5bc3cc12df</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = 'https://assets.ajio.com/medias/sys_master/root/20230321/HAHB/64195210f997dde6f41b1607/puma_black_low-tops_lace-up_sports_shoes.jpg']</value>
      <webElementGuid>675627cb-24ff-463a-83d6-876cfe4297cf</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
