<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_Tomorrow_product-card_current-prod-img__a55c27</name>
   <tag></tag>
   <elementGuidId>3ae0f83d-2c0b-4479-8692-cbe26db7d482</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#PERS40611 > a.product-card_card-container__1oJLc > figure.product-card_image-holder__11Rdr.product-card_image-padding__5kaUl > div > img.product-card_current-prod-img__HhplZ.product-card_prod-img__2K5WE</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='PERS40611']/a/figure/div/img</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>94e1d964-969b-4120-b644-9002792dd702</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>itemprop</name>
      <type>Main</type>
      <value>image</value>
      <webElementGuid>f4b20a33-5ae8-40f1-9a47-11a68586152b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-imageurl</name>
      <type>Main</type>
      <value>/images/pr/l/v20220926092017/personalised-love-affair-led-cushion_1.jpg</value>
      <webElementGuid>e7ff343e-a5f9-42fb-9855-0e7e6b6593d4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>alt</name>
      <type>Main</type>
      <value>Personalised Diwali Wishes Combo</value>
      <webElementGuid>a2c75820-b22c-431b-a052-171fbc497e27</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>/images/pr/l/v20220926092017/personalised-love-affair-led-cushion_1.jpg</value>
      <webElementGuid>f0fb1a62-0667-4dfb-9d01-601bf997d193</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>decoding</name>
      <type>Main</type>
      <value>async</value>
      <webElementGuid>8df99ff0-fa27-42e7-83be-ee1ae30519cf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-nimg</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>945101b1-c554-4058-978a-83db3d7d29ea</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>product-card_current-prod-img__HhplZ product-card_prod-img__2K5WE</value>
      <webElementGuid>49d4e104-7351-41f4-953d-ee88d71c51e6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;PERS40611&quot;)/a[@class=&quot;product-card_card-container__1oJLc&quot;]/figure[@class=&quot;product-card_image-holder__11Rdr product-card_image-padding__5kaUl&quot;]/div[1]/img[@class=&quot;product-card_current-prod-img__HhplZ product-card_prod-img__2K5WE&quot;]</value>
      <webElementGuid>33d6b737-5c81-4e20-ad0c-5ca50fe8f1c8</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='PERS40611']/a/figure/div/img</value>
      <webElementGuid>9964887b-4a94-45a1-8b3d-1a9b73af9a0f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>//img[@alt='Personalised Diwali Wishes Combo']</value>
      <webElementGuid>927f9a9c-3d27-4f9f-afee-4be8c432385a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/div/div/a/figure/div/img</value>
      <webElementGuid>39455e01-d858-4ad9-a45d-ceba64c10c15</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@alt = 'Personalised Diwali Wishes Combo' and @src = '/images/pr/l/v20220926092017/personalised-love-affair-led-cushion_1.jpg']</value>
      <webElementGuid>7147a296-705c-43e2-8096-08e05da9089c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
