<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Search</name>
   <tag></tag>
   <elementGuidId>6d3ef1b4-92a9-4f96-aee8-c734cf1293ff</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>a.btn.btn-primary.search-table</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='rootCtrlId']/div[3]/div[2]/div/div/form/div[2]/a[2]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>205ece0b-b5aa-4355-ab83-13700f2a212a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>#</value>
      <webElementGuid>be43529a-1364-4d6f-92bf-799593530d0a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn btn-primary search-table</value>
      <webElementGuid>1622f1ef-4ab0-438e-b9e9-7804a747efa6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-disabled</name>
      <type>Main</type>
      <value>(vm.clientSearchForm.$invalid)</value>
      <webElementGuid>f41294f4-53f7-46a0-84ee-fbace343e01c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-click</name>
      <type>Main</type>
      <value>vm.submit()</value>
      <webElementGuid>b6e0b967-4338-4ba6-8a94-4f300ee30531</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>  Search</value>
      <webElementGuid>da969a71-c0cc-4213-891b-67c9f76deda2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;rootCtrlId&quot;)/div[@class=&quot;page-container&quot;]/div[@class=&quot;content-wrapper&quot;]/div[@class=&quot;ng-scope&quot;]/div[@class=&quot;panel panel-body no-header&quot;]/form[@class=&quot;form form-horizontal ng-pristine ng-valid ng-valid-maxlength&quot;]/div[@class=&quot;form-group text-right&quot;]/a[@class=&quot;btn btn-primary search-table&quot;]</value>
      <webElementGuid>4b309749-6c1a-4993-a3ed-b464ebe09f82</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='rootCtrlId']/div[3]/div[2]/div/div/form/div[2]/a[2]</value>
      <webElementGuid>8c23fdc2-7577-451a-a1cc-6144b721cb74</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Client Name'])[1]/following::a[2]</value>
      <webElementGuid>cbc350b0-b379-4dda-b425-a5d9e4a87b3b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Client Code'])[1]/following::a[2]</value>
      <webElementGuid>5b8ec935-97fc-4bdd-bb15-3f2d8a21efc3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Complaints Policy |'])[1]/preceding::a[1]</value>
      <webElementGuid>1d8e50e0-d576-468c-882e-55fb659b524e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Privacy Policy |'])[1]/preceding::a[2]</value>
      <webElementGuid>98ab2819-cdf2-4e9e-8bfc-083b0568ba7b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Search']/parent::*</value>
      <webElementGuid>411dc363-71f5-4510-a45f-7f61792bc1ab</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>(//a[contains(@href, '#')])[11]</value>
      <webElementGuid>17b1a3ed-9d86-461a-a396-546479b15277</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//a[2]</value>
      <webElementGuid>9a987142-9a9e-4a3a-88f2-31742a576411</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '#' and (text() = '  Search' or . = '  Search')]</value>
      <webElementGuid>2bfcb6f8-0ddf-4adb-951b-506256c40853</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
