<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_CL0004687</name>
   <tag></tag>
   <elementGuidId>cd8172fb-3f87-4077-b47a-15719e14a571</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#1686744697800-7-uiGrid-0006-cell > form[name=&quot;editSearchForm&quot;] > button.custom-button.ng-binding</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>(//button[@type='submit'])[8]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>58b50c92-3a5e-4770-a137-610da11a965d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>submit</value>
      <webElementGuid>9646241f-bbd5-4c4d-9b23-42159c3e717f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>custom-button ng-binding</value>
      <webElementGuid>ecaae26d-0440-406c-93e4-560dde427254</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>CL0004687</value>
      <webElementGuid>5172dece-660b-419c-beed-cafa4c6e7e43</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;1686744697800-7-uiGrid-0006-cell&quot;)/form[@class=&quot;ng-pristine ng-valid ng-scope&quot;]/button[@class=&quot;custom-button ng-binding&quot;]</value>
      <webElementGuid>200d9af4-ae8a-4b09-a34b-4fb1d84c046a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//button[@type='submit'])[8]</value>
      <webElementGuid>400ed1cb-168c-4f56-8310-2737458b756d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='1686744697800-7-uiGrid-0006-cell']/form/button</value>
      <webElementGuid>5eead10d-1075-4d90-8f41-c2c080407d76</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Active'])[7]/following::button[1]</value>
      <webElementGuid>c0e95be9-2545-4df7-97b7-7ba4a169027e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Kitten Kitten'])[1]/following::button[1]</value>
      <webElementGuid>50591436-66f7-4736-861a-05836179c69b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Individual'])[8]/preceding::button[1]</value>
      <webElementGuid>54b1eb6d-2bf9-4f4b-b48d-279faa26070c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Gopal Gopal'])[1]/preceding::button[1]</value>
      <webElementGuid>f1dda386-8ca3-4892-b711-a8d7a76f82f5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='CL0004687']/parent::*</value>
      <webElementGuid>16f536b2-f0ba-4964-8eab-af39ea67cc71</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[8]/div/div/form/button</value>
      <webElementGuid>1b913f62-5298-4c35-90cb-fde164550ecd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'submit' and (text() = 'CL0004687' or . = 'CL0004687')]</value>
      <webElementGuid>e8f7fbde-4ceb-4045-9eb7-f1fd1d5d3039</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
