<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>p_8</name>
   <tag></tag>
   <elementGuidId>5b4a62e2-b3d9-491c-9324-2439e3729195</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='sizeButtonsContainer']/div[2]/div[3]/div/button/p</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>p</value>
      <webElementGuid>6fa0105f-06c3-4072-a40e-8bfc6f6338f3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>size-buttons-unified-size</value>
      <webElementGuid>0c7a1a2f-2210-4365-80c4-11547b878391</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>8</value>
      <webElementGuid>994279a2-383f-4e4c-aad5-32789523518d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;sizeButtonsContainer&quot;)/div[@class=&quot;size-buttons-size-buttons&quot;]/div[@class=&quot;size-buttons-tipAndBtnContainer&quot;]/div[@class=&quot;size-buttons-buttonContainer&quot;]/button[@class=&quot;size-buttons-size-button size-buttons-size-button-default&quot;]/p[@class=&quot;size-buttons-unified-size&quot;]</value>
      <webElementGuid>5dae6890-4b6a-41db-ad6c-69c3a73c0079</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='sizeButtonsContainer']/div[2]/div[3]/div/button/p</value>
      <webElementGuid>3c36b782-df06-444a-9b3f-5ecc85e86ca5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='To Fit Foot Length - 28.0cm'])[1]/following::p[1]</value>
      <webElementGuid>cdfbf24a-f82f-4f3c-9dde-686a46cadaa2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Body Measurement:'])[2]/following::p[1]</value>
      <webElementGuid>9d48b6b8-d384-447e-9b4a-0c6d602467c9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Hide'])[3]/preceding::p[1]</value>
      <webElementGuid>63149ec5-0876-43f5-ba73-8eecfb0ae6ec</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Body Measurement:'])[3]/preceding::p[1]</value>
      <webElementGuid>17dd7bf7-81b8-4fcf-9aae-a0de1a5810de</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='8']/parent::*</value>
      <webElementGuid>35e07ee5-16d6-4746-bd13-63553938d880</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/button/p</value>
      <webElementGuid>0942e669-aaee-4f07-b155-4f6a02a77d93</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//p[(text() = '8' or . = '8')]</value>
      <webElementGuid>f155bcca-22b2-4d0d-9e13-2eeaa20829ef</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
