<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_MOVE TO WISHLIST_itemComponents-base-in_6dd8b4</name>
   <tag></tag>
   <elementGuidId>1db67c3d-de41-474f-ae7c-b50f1c0700d2</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.itemComponents-base-invisibleBackDrop</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='cartItemsList']/div/div/div/div[2]/div/div/div</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>d2bcd3ea-0aed-45eb-abef-c2fac56ab23f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>itemComponents-base-invisibleBackDrop</value>
      <webElementGuid>ec26f79d-513e-4dc2-88c3-de3bee308ac9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;cartItemsList&quot;)/div[@class=&quot;itemContainer-base-itemMargin&quot;]/div[1]/div[@class=&quot;item-base-item&quot;]/div[@class=&quot;itemContainer-base-item&quot;]/div[@class=&quot;itemContainer-base-itemLeft&quot;]/div[@class=&quot;itemComponents-base-selectionIconContainer itemContainer-base-selectionIndicator&quot;]/div[@class=&quot;itemComponents-base-invisibleBackDrop&quot;]</value>
      <webElementGuid>5e8d1aea-9c41-4f59-8294-9fa7d9e7ce5f</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='cartItemsList']/div/div/div/div[2]/div/div/div</value>
      <webElementGuid>639f13af-cf53-4a70-abbf-ace1b07ff5d3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[5]/div/div/div/div[2]/div/div/div</value>
      <webElementGuid>781f0b3f-ed7e-409e-9114-b35cf6351ef7</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
