<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_NBOX - Blue Silicon Plain Cases Compatibl_e3ad25</name>
   <tag></tag>
   <elementGuidId>bf7cc4c2-5771-45ff-b51e-c1255121ae67</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='ajaxWidget-products_c_widget_cxe-0']/div[4]/a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>33563435-ecbe-4c6e-ba37-d02fe553d616</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>product-card pp dp-widget-link </value>
      <webElementGuid>86cbccf2-c2b3-4754-889c-594400fc975b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>https://www.snapdeal.com/product/nbox-green-silicon-plain-cases/683610574677</value>
      <webElementGuid>9323ffb6-19b3-4799-a25d-f8bdd3f79751</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>cat</name>
      <type>Main</type>
      <value>undefined</value>
      <webElementGuid>47d24eeb-f414-4fbf-8a4f-41478a399312</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>bucket</name>
      <type>Main</type>
      <value>undefined</value>
      <webElementGuid>ae2399e5-038d-452e-95af-c573f15a9833</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>pog</name>
      <type>Main</type>
      <value>683610574677</value>
      <webElementGuid>ae9c0178-0f41-4ec9-b7ca-933fac3c9559</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>target</name>
      <type>Main</type>
      <value>_blank</value>
      <webElementGuid>fda04352-f75e-405c-b823-f1fce2331189</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>index</name>
      <type>Main</type>
      <value>3</value>
      <webElementGuid>5feff1ef-1395-4be0-be02-a5746a2a6181</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>             NBOX - Blue Silicon Plain Cases Compatible For iPhone 13 ( Pack of 1 )                                                         Rs 1,299           Rs 399                69% OFF                       VIEW DETAILS   </value>
      <webElementGuid>0545738e-6379-4c7c-be95-df7862ac8fc8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ajaxWidget-products_c_widget_cxe-0&quot;)/div[@class=&quot;product-relative ceeProd dp-widget-link js-omni width20 favDp&quot;]/a[@class=&quot;product-card pp dp-widget-link&quot;]</value>
      <webElementGuid>4e42cbbb-3415-4a91-b104-3b3b062c5ed1</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='ajaxWidget-products_c_widget_cxe-0']/div[4]/a</value>
      <webElementGuid>b0460af6-c07e-435d-9553-8262a22a992c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='VIEW DETAILS'])[3]/following::a[1]</value>
      <webElementGuid>56f31ae4-ab9a-4f08-8345-718448401dfb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Rs 949'])[1]/following::a[1]</value>
      <webElementGuid>dc31f350-a632-4a73-9810-035f846efa40</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, 'https://www.snapdeal.com/product/nbox-green-silicon-plain-cases/683610574677')]</value>
      <webElementGuid>3cb89455-eb43-44e5-a371-06252ed03ec6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div[4]/a</value>
      <webElementGuid>baa7be8c-01f8-4f56-a729-7d347e1d20c3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'https://www.snapdeal.com/product/nbox-green-silicon-plain-cases/683610574677' and (text() = '             NBOX - Blue Silicon Plain Cases Compatible For iPhone 13 ( Pack of 1 )                                                         Rs 1,299           Rs 399                69% OFF                       VIEW DETAILS   ' or . = '             NBOX - Blue Silicon Plain Cases Compatible For iPhone 13 ( Pack of 1 )                                                         Rs 1,299           Rs 399                69% OFF                       VIEW DETAILS   ')]</value>
      <webElementGuid>5faf72ed-b1aa-4509-9c16-d1ceb8aee04d</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
