<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_World Test Championship</name>
   <tag></tag>
   <elementGuidId>6a1a8ebd-9033-4322-8fce-74a5cf334698</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//nav[@id='cb-main-menu']/div[6]/nav/a</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>53c1af58-8d1c-4065-acf2-17e71b780b1c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>cb-subnav-item</value>
      <webElementGuid>ca02839f-e8e1-4c0f-837c-22b87e86e923</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>target</name>
      <type>Main</type>
      <value>_self</value>
      <webElementGuid>bf9bc55f-a973-428c-ac55-46c02d97da89</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/cricket-stats/points-table/test/icc-world-test-championship</value>
      <webElementGuid>ccdf83dd-bbb1-451d-a6d9-ba5f2a1d515c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>World Test Championship</value>
      <webElementGuid>e56a0fe8-83cc-4069-9f68-1944caf958c4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>World Test Championship</value>
      <webElementGuid>f11b3706-082b-4350-bf40-de5721b0456d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;cb-main-menu&quot;)/div[@class=&quot;cb-subnav cb-hm-mnu-itm feature-button cursor-pointer&quot;]/nav[@class=&quot;cb-sub-navigation&quot;]/a[@class=&quot;cb-subnav-item&quot;]</value>
      <webElementGuid>a8d23e90-322e-4ef0-be7d-2430a72fcdfb</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//nav[@id='cb-main-menu']/div[6]/nav/a</value>
      <webElementGuid>74f53bad-0513-47ca-8030-2966b10d9ce2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>(//a[contains(text(),'World Test Championship')])[2]</value>
      <webElementGuid>3debda28-46ee-4afa-8ea0-7771675b1ddf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='ICC Rankings - Women'])[1]/following::a[1]</value>
      <webElementGuid>f7b35ca7-8ee5-42ed-b316-d9fca9a1af43</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='IPL Live Stream'])[1]/preceding::a[1]</value>
      <webElementGuid>dd076fe0-cc33-4b94-a791-3462b1db5c08</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='World Cup Super League'])[1]/preceding::a[2]</value>
      <webElementGuid>f82bbc55-2d94-4ce3-9ad2-71c8344ecda5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='World Test Championship']/parent::*</value>
      <webElementGuid>cb751a9b-e685-4aa1-ab21-cc9a5a90b46b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, '/cricket-stats/points-table/test/icc-world-test-championship')]</value>
      <webElementGuid>58a94061-ea03-42b3-89b9-a05bae13c8ba</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[6]/nav/a</value>
      <webElementGuid>15eafb24-b705-4d40-aa01-a1c5272c606a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '/cricket-stats/points-table/test/icc-world-test-championship' and @title = 'World Test Championship' and (text() = 'World Test Championship' or . = 'World Test Championship')]</value>
      <webElementGuid>a04d4866-916f-405b-8096-8b68198e4902</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
